# Generated by Django 2.1 on 2018-11-28 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('address', models.CharField(max_length=100, verbose_name='Mailing Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zipcode', models.CharField(max_length=20, verbose_name='Zipcode')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone number')),
                ('is_employed', models.BooleanField(verbose_name='Are you Employed?')),
                ('employer', models.CharField(blank=True, max_length=50, verbose_name='If currently employed then who is your current employer?')),
                ('family_size', models.IntegerField(verbose_name='How many members in the family including you?')),
                ('items_needed', models.TextField(max_length=200, verbose_name='What items do you need today?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('picked_up', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.Customer')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='VisitItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_items', to='pantry.Item')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.Visit')),
            ],
        ),
    ]
